development:
  adapter: postgresql
  encoding: utf8
  database: ow_development
  pool: 5
  timeout: 5000
  username: openwallet
  password: ow2017
  host: localhost
  port: 5432

test: &test
  adapter: postgresql
  encoding: utf8
  database: ow_test
  pool: 5
  timeout: 5000
  username: openwallet
  password: ow2017
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['POSTGRES_DB'] %>
  pool: 5
  timeout: 5000
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PWD'] %>
  host: localhost
  port: 5432

cucumber:
  <<: *test