development: &development
  adapter: postgresql
  encoding: utf8
  database: ow_development
  pool: 5
  timeout: 5000
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PWD', 'password') %>
  host: localhost
  port: 5432

test: &test
  <<: *development
  database: ow_test

production:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['POSTGRES_DB'] %>
  pool: 5
  timeout: 5000
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PWD'] %>
  host: localhost
  port: 5432

cucumber:
  <<: *test
